# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8696d882d3bc8cfcbb609d85124c6faca3ca0dcccee71b9a03d58b50bfb6531755e22e42072b0931592c3007a58273d483b7f6b4c4f950e8bc7065c2675b5f98

test:
  secret_key_base: 4a6c24b1faad793b258dcec055503b6a6400025db2459ea8e8d5aa924bc92a25b6a5be0181aafd2552e1398a7f6746782edb2582a14eb280d27902938748a78c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
