# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf12c745a54b41b05e2618e3afef5158d254e647490a24c84595abc19d6327b43c511ac1e3dda6a8449a905c96ea1054f816e406b4e0b7b4a0874826696fd1c7

test:
  secret_key_base: 9d0b762e3ab4a41a77b3e22f6fc7eb6c5ddb6bc77827fabb7178dd66b02f3b62ef0996e871d667bb2d06e0b1d5b3c705a80477ebbed84f0e9358f9760b8f9bf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
